baseURL = 'https://www.terrapeneornata.com/'
languageCode = 'en-us'
title = 'Terrapene Ornata'
theme = 'paper'

[params]
rss = true
bluesky = 'mikegruz.bsky.social'
mastodon = 'https://mstdn.social/@mikegruz'
github = 'https://github.com/MikeGruz'

# profile
name = 'Mike Gruszczynski'
bio = "Mike's Blog"

# misc
monoDarkIcon = true